scenario:
  name: "Multi-Target Engagement"
  description: "Multiple hostile targets with prioritization"
  battlespace: "configs/battlespace/default_battlespace.yaml"
  update_rate: 50
  
  interceptor:
    id: "interceptor_1"
    aircraft: "configs/aircraft/interceptor_drone.yaml"
    team: "blue"
    initial_state:
      position: [25000, 25000, 3000]
      velocity: 50.0
      heading: 0.0
      fuel_fraction: 1.0
      
  targets:
    - id: "high_priority_target"
      aircraft: "configs/aircraft/target_fighter.yaml"
      team: "red"
      behavior: "aggressive"
      threat_level: "hostile"
      priority: "high"
      initial_state:
        position: [30000, 30000, 3000]
        velocity: 45.0
        heading: 225.0
        
    - id: "medium_priority_target"
      aircraft: "configs/aircraft/target_basic.yaml"
      team: "red"
      behavior: "evasive"
      threat_level: "hostile"
      priority: "medium"
      initial_state:
        position: [20000, 35000, 2000]
        velocity: 40.0
        heading: 180.0
        
    - id: "low_priority_target"
      aircraft: "configs/aircraft/target_basic.yaml"
      team: "red"
      behavior: "patrol"
      threat_level: "unknown"
      priority: "low"
      initial_state:
        position: [35000, 20000, 2500]
        velocity: 35.0
        heading: 90.0
        
  objectives:
    primary:
      - type: "prioritized_intercept"
        engagement_order: ["high_priority_target", "medium_priority_target"]
      - type: "time_limit"
        max_time: 400
    secondary:
      - type: "all_targets_neutralized"
      - type: "fuel_efficiency"
        min_fraction: 0.1
        
  termination:
    time_limit: 600