scenario:
  name: "Basic Intercept Training"
  description: "Single target interception in clear weather"
  battlespace: "configs/battlespace/default_battlespace.yaml"
  update_rate: 50  # Hz
  
  # Interceptor configuration
  interceptor:
    id: "interceptor_1"
    aircraft: "configs/aircraft/interceptor_drone.yaml"
    team: "blue"
    initial_state:
      position: [5000, 5000, 2000]
      velocity: 50.0
      heading: 0.0  # degrees
      fuel_fraction: 1.0
    guidance_mode: "autonomous"
      
  # Target Aircraft
  targets:
    - id: "target_1"
      aircraft: "configs/aircraft/target_basic.yaml"
      team: "red"
      behavior: "waypoint"
      threat_level: "hostile"
      initial_state:
        position: [25000, 25000, 2500]
        velocity: 40.0
        heading: 180.0
      waypoints:
        - [25000, 20000, 2500]
        - [20000, 15000, 2000]
        - [15000, 10000, 2000]
      
  # Success Criteria
  objectives:
    primary:
      - type: "intercept"
        target_id: "target_1"
        range: 50  # meters
        time_limit: 300  # seconds
    secondary:
      - type: "fuel_remaining"
        min_fraction: 0.2
      - type: "no_terrain_collision"
        
  # Termination Conditions
  termination:
    time_limit: 600  # seconds
    
  # Data Recording
  recording:
    enabled: true
    frequency: 10  # Hz